version: '3.7'
services:
  doka-app:
    build:
      context: .
      dockerfile: docker/php${DOKA_APP_PHP_VERSION}-apache/Dockerfile
      args:
        - APACHE_DOCUMENT_ROOT=${DOKA_APP_APACHE_DOCUMENT_ROOT}
        - HOST_USER_ID=${DOKA_HOST_USER_ID}
    environment:
      - XDEBUG_MODE=${DOKA_APP_XDEBUG_MODE}
      - XDEBUG_CONFIG=client_host=${DOKA_APP_XDEBUG_CLIENT_HOST} client_port=${DOKA_APP_XDEBUG_CLIENT_PORT}
      - XDEBUG_SESSION=1
      - PHP_IDE_CONFIG=serverName=doka-app
    volumes:
      - './../:/var/www/html'
    ports:
      - '${DOKA_APP_HOST_PORT}:80'
  doka-mysql:
    build: docker/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DOKA_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOKA_MYSQL_DATABASE}
      MYSQL_USER: ${DOKA_MYSQL_USER}
      MYSQL_PASSWORD: ${DOKA_MYSQL_PASSWORD}
    ports:
      - '${DOKA_MYSQL_HOST_PORT}:3306'

